language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
before_install:
  - touch spec/config.yml
  - echo 'ws:' >> spec/config.yml
  - echo '  endpoint:' $WS_DIRECTLOG_ENDPOINT >> spec/config.yml
  - echo '  login:' $WS_DIRECTLOG_LOGIN >> spec/config.yml
  - echo '  password:' $WS_DIRECTLOG_PASSWORD >> spec/config.yml
  - sudo apt-get install freetds-dev
  - gem install bundler
before_script:
  - bundle
bundler_args: --without test --retry 3
script:
  - bundle exec rspec spec
